### ISSUE TITLE
Wrong links after renaming

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vmware.vmware_rest#100]
##### SUMMARY
After renaming this repo from `vmware_rest` to `vmware.vmware_rest`, there are some links that need to be updated. For example in galaxy.yml:

> repository: https://github.com/ansible-collections/vmware_rest.git

to

> repository: https://github.com/ansible-collections/vmware.vmware_rest.git

GitHub will redirect `vmware_rest` links to `vmware.vmware_rest`, but I think it would be better to have the correct links.

##### ISSUE TYPE
- Documentation Report

**Comment by goneri** [comment]
thank you @mariolenz.
