### ISSUE TITLE
Links in Read Me on Ansible Galaxy are not valid

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vmware.vmware_rest#101]
##### SUMMARY
The links in `README.md` don't work because they refer to `vmware_rest.git` instead of `vmware_rest`. This also affects the "Read Me" on galaxy.

The `vmware` collection had the same issue, ansible-collections/community.vmware#389. 

After renaming this repo, I think you should change `vmware_rest.git` to `vmware.vmware_rest` while you're at it. The `vmware` collection was renamed after fixing this so I had to issue PR ansible-collections/community.vmware#396, but you can fix this in one go.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
README.md

**Comment by goneri** [comment]
This listing in the README.md is autogenerated, I use to refresh it before the releases.
See: https://github.com/ansible-collections/community.vmware#publishing-new-version
