### ISSUE TITLE
All doc links in readme.md are dead

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#113]
##### SUMMARY

Hi when clicking a doc link in the readme.md it is dead, I have yet to find one that works.
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by RobVerduijn** [comment]
All links start with https://github.com/ansible-collections/vmware.vmware_rest.git
should be https://github.com/ansible-collections/vmware.vmware_rest

**Comment by Akasurde** [comment]
@RobVerduijn Thanks for reporting this issue. Please review https://github.com/ansible-collections/vmware.vmware_rest/pull/115
