### ISSUE TITLE
upload/download/move files in datastore 

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#116]
##### SUMMARY

Create a module to manipulate files in a datastore.
ie
- create a folder
- delete a folder
- rename/move a folder
- upload a file
- delete a file
- rename/move a file

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vcenter_datastore_file
##### ADDITIONAL INFORMATION

for uploading files/images to the vcenter datastore
also renaming or moving of the file/dir to keep things clean

```yaml

```

**Comment by gravesm** [comment]
@RobVerduijn thank you for the report. We try to map all models on top of the models provided by VMware. As far as we are aware, there is no such API to match this requirement. In the mean time, we suggest you try vsphere_copy and vsphere_file in the community collection.
