### ISSUE TITLE
use fqcn in documentation

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#120]
##### SUMMARY

Hello, with the release of ansible 2.10 the collections have been pushed forward as the way to go.
The release notes describe the use of [fqcn](https://github.com/ansible-collections/overview/blob/main/README.rst#terminology)

Currently the modules doc links make use of the fqcn, however the documentation does not make use of the fqcn.

Shouldn't the documentation make use of the fqcn in stead of only the short module name ?

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by goneri** [comment]
This would be indeed a nice change to be more consistent with the other collections.
