### ISSUE TITLE
vcenter_vm_power_info does not mention state option, vm identifier should be vm moid.

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#123]
##### SUMMARY

Hello,
The vcenter_vm_power_info has no entry for the state option.
The vm option suggests that there is a state option (Required with state=['get'] )

Also the vm option should not use the word identifier.
identifier suggest uuid or name, but the moid of the vm is needed here

Rob

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by goneri** [comment]
Both are two valid points indeed. Thanks for reporting them.

**Comment by goneri** [comment]
I close the issue since the documentation is much better than in september and the problem you mention has been addressed.
