### ISSUE TITLE
no official redhat rpm for aiohttp

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#125]
##### SUMMARY

Hi,
I just found this [document](https://www.ansible.com/blog/introducing-the-vmware-rest-ansible-content-collection)
~~~
<frustration mode>
~~~
Since you are redhat.
aiohttp is vital for this project, this project is backed by redhat
Why is there only an epel package for aiohttp ?

Since redhat is so proud on selling this as the next big thing.
Please provide an official aiohttp rpm so rhel admins don't need to include the epel repos and get into very long discussions about it with support.
~~~
</frustration mode>
~~~
Now back to centos :yum:

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by towster** [comment]
Not sure if this is really helpful but they do have an aiohttp package in the satellite repo it looks like.. 

Search for aiohttp here:
https://access.redhat.com/downloads/content/250/ver=6.8/rhel---7/6.8.1/x86_64/packages

**Comment by goneri** [comment]
Thanks for raising this. If you run RHEL7 or RHEL8, we will soon provide a container with aiohttp and Ansible. This Execution Environment will be the official way to run the Ansible, and it will address this dependency issue.
In the meantime, you can prepare a Python virtual environment. This is anyway often the best way to run Ansible when you want to pine on a specific version, or use some extra dependencies. I've refreshed the documentation to explain how to do that.
