### ISSUE TITLE
documentation of vm_module really needs work

### ISSUE THREAD

**Issue by RobVerduijn** [ansible-collections/vmware.vmware_rest#126]
##### SUMMARY

Hello,

Today I've managed to create a vm using the vm_module, this was not an easy task.
I've been busy trying to figure out what the correct syntax was by using the doc, example, vmware api documentation and reading the python code.
After quite some time I managed to launch a heavily customized vm.

The issues I've faced during this proces:
* in the documentation parameters , cdroms, disks, and nics really could use another column for readability.
  * it is really hard to read and see what options are for which dict,another column would solve this.
  * ie: cdroms is a list containing nested dicts, try to see what the legal values are for which key is next to impossible
  * same goes for floppies I gues, but I don't use those anymore
  * it is very hard to see which option will be defaulted by the vcenter if omitted and to what value.
  * it is very hard to see what option is required when another option is set (ie: nics backend=>network requires backend=>type)
* MOID is used everywhere, this should mentioned that you need to find the moid for the network/datastore/cluster/vm/folder
  * the option to use a name in stead of a moid would have been nice, converting a name to moid is easy for one nic, however creating a definition with multiple networks will be a challenge if you know only the network names.
  * name to moid conversion takes a lot of boilerplate code in ansible, please implement something to make the conversion easy [vmware kb](https://kb.vmware.com/s/article/1017126)
* only a very simple default create vm example is included, please include one that has custom nics/disks/cdroms it would have saved me a lot of time
* an example showing custom adapters ide/sata/scsi will help as well (for me the default were fine)
* an example for the boot and boot_devices
* maybe also for serial and parallel ports (although this is rather exotic, I can't remember any situation where I could have used this)

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by Akasurde** [comment]
@RobVerduijn Thanks for the feedback. VMware REST modules are autogenerated from the VMware REST OpenAPI JSON files. The documentation is also autogenerated from the same JSON files. I think we will need to add something to overlay documentation with examples to simplify the user experience. 
These modules are in the nascent stage and definitely improve over the period of time. 

Thanks for the feedback.

**Comment by RobVerduijn** [comment]
I forgot to mention, 
an example of how to get a vm moid when you only know the name would be a good thing
not every ansible admin is good with filters

**Comment by Akasurde** [comment]
You can use following example to get MoID of VM by 

```yaml
---
- hosts: localhost
  tasks:
    - name: Get VM moid
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_username: administrator@vsphere.local
        vcenter_password: Esxi@123$%
        vcenter_hostname: 10.65.201.128
        filter_names:
          - centos_7
      register: r

    - debug:
        msg: "{{ r.value[0].vm }}"
```

```
TASK [Get VM] *********************************************************************************
ok: [localhost] => {"_debug_info": {"operation": "get", "status": 200}, "changed": false, "value": [{"cpu_count": 1, "memory_size_MiB": 2048, "name": "centos_7", "power_state": "POWERED_ON", "vm": "vm-20"}]}

TASK [debug] **********************************************************************************
ok: [localhost] => {
    "msg": "vm-20"
}
```

**Comment by Akasurde** [comment]
Personally, I am fan of using moid since they are unique in vcenter environment. In the past, we have seen a lot of issues with name+folder to identify VMware objects since the names are not unique.

**Comment by goneri** [comment]
@RobVerduijn we are actively working on the documentation, but it would be great if you can share your own playbooks, for instance on a blog post.

Regarding vcenter_vm parameters, I would advice to create a light VM and use the vcenter_vm_hardware_* modules do adjust it after. It would be easier.

**Comment by RobVerduijn** [comment]
> You can use following example to get MoID of VM by
> 
> ```yaml
> ---
> - hosts: localhost
>   tasks:
>     - name: Get VM moid
>       vmware.vmware_rest.vcenter_vm_info:
>         vcenter_username: administrator@vsphere.local
>         vcenter_password: Esxi@123$%
>         vcenter_hostname: 10.65.201.128
>         filter_names:
>           - centos_7
>       register: r
> 
>     - debug:
>         msg: "{{ r.value[0].vm }}"
> ```
> 
> ```
> TASK [Get VM] *********************************************************************************
> ok: [localhost] => {"_debug_info": {"operation": "get", "status": 200}, "changed": false, "value": [{"cpu_count": 1, "memory_size_MiB": 2048, "name": "centos_7", "power_state": "POWERED_ON", "vm": "vm-20"}]}
> 
> TASK [debug] **********************************************************************************
> ok: [localhost] => {
>     "msg": "vm-20"
> }
> ```
Hi,
I meant for the documentation.

The filter option is nice I completely missed it while writing my plays.
I was already wondering how these modules would perform in HUGE environments, that should take care of it.

My issue with this way of working is that this will always be needed and forces you to write some boyler plate scripts that you will be using a lot. ( already experiencing that )

Which is why I made the suggestion for something to make this easier, maybe  a custom lookup or a filter for the collection ?
( whatever works best for you )

Rob

**Comment by RobVerduijn** [comment]
@goneri 
```
> @RobVerduijn we are actively working on the documentation, but it would be great if you can share your own playbooks, for instance on a blog post.
```
I'm writing my plays while being paid for as a consultant, I'll have to get permission first.
```
> 
> Regarding vcenter_vm parameters, I would advice to create a light VM and use the vcenter_vm_hardware_* modules do adjust it after. It would be easier.
```
I did consider that path, 
do me a favor and try to create a play for the following scenario:
- assuming a working vsphere environment and you have admin credentials.
- however, in real life you know only the friendly names...so all the moid or uuid have to be determined by your play.
- create a vm using the example from the vm_module ( feel free to adjust it, the only limit is it may not contain a cdrom device )
- add a cdrom  which contains an iso dvd image from the datastore 


Then run it to see it really works.

**Comment by goneri** [comment]
The documentation is now online and it comes with some CDROM management examples: https://docs.ansible.com/ansible/devel/scenario_guides/guide_vmware_rest.html

**Comment by RobVerduijn** [comment]
I've read it, looks great.

you should add that link to the main readme.md

Rob

**Comment by RobVerduijn** [comment]
After using the collection some more, I found that creating a clone and a linked clone is a challenge.

So maybe add the following three scenarios:
- create a vm    # why I didn't notice this one isn't in there before is a mistery
- create a clone from a vm
- create a linked clone from a vm

Rob

**Comment by goneri** [comment]
I close this now we've got https://docs.ansible.com/ansible/devel/scenario_guides/guide_vmware_rest.html

If you find any problem with the docuentation, don't hesitate to open new issues. Regarding the clone management, do you have some playbooks to share?

**Comment by RobVerduijn** [comment]
Hi,

> If you find any problem with the docuentation, don't hesitate to open new issues. Regarding the clone management, do you have some playbooks to share?

I've not managed to get the clone option to work yet, I got all kinds of weird errors from the system and I needed to get this working so I'm using parts of some old plays that clone a new vm from a template in a the content library.
These rely heavily on the uri module to make the rest api calls. (using a token for auth that I obtained first with the uri module)

Rob
