### ISSUE TITLE
Cannot create a resource pool following current documentation

### ISSUE THREAD

**Issue by matthewcosgrove** [ansible-collections/vmware.vmware_rest#153]
##### SUMMARY
Cannot create a resource pool following current documentation

From what I gather, I need to provide the name of the new resource pool and it's parent. This is an accordance with all documented parameters which state `Required with state=['present']`

My choice of parent comes from viewing the vcenter UI via Hosts and Clusters. Within the playbook below I retrieve the moid of the cluster I want to create the resource pool under (the cluster name was already set where I am running the playbook via the env var GOVC_CLUSTER so I just reuse that to filter on)

So far I have 

```
- name: Create resource pool
  hosts: localhost
  vars:
    existing_cluster: "{{ lookup('env', 'GOVC_CLUSTER') }}"

  collections:
  - vmware.vmware_rest
  tasks:
  - name: "get parent cluster for resource pool"
    vcenter_cluster_info:
      filter_names:
      - "{{ existing_cluster }}"
    register: my_cluster
  - name: "ensure resource pool created"
    vcenter_resourcepool:
      name: "new-resource-pool"
      parent: "{{ my_cluster.value[0].cluster }}"
    register: my_resource_pool
  - debug: msg="{{ my_resource_pool }}"
```

but this results in 

```
fatal: [localhost]: FAILED! => {
    "_debug_info": {
        "operation": "create",
        "status": 404
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "cpu_allocation": null,
            "memory_allocation": null,
            "name": "new-resource-pool",
            "parent": "domain-c2050",
            "resource_pool": null,
            "state": "present",
            "vcenter_hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vcenter_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vcenter_rest_log_file": null,
            "vcenter_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vcenter_validate_certs": false
        }
    },
    "type": "com.vmware.vapi.std.errors.not_found",
    "value": {
        "error_type": "NOT_FOUND",
        "messages": [
            {
                "args": [],
                "default_message": "Resource pool with identifier '{}' does not exist.",
                "id": "com.vmware.api.vcenter.resourcepool.not_found"
            }
        ]
    }
}
```

Why would it error stating the obvious that the resource pool does not exist when to me I'm clearly trying to "create" it as indicated by `"state": "present"`?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
vmware.vmware_rest.vcenter_resourcepool_module.rst

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

**Comment by Akasurde** [comment]
@matthewcosgrove Thanks for reporting this issue. Could you please specify the vCenter version? 

I have vCenter Server 6.5 and there is no API to create Resource pool.

<img width="1157" alt="Screenshot 2020-10-20 at 20 07 27" src="https://user-images.githubusercontent.com/633765/96601703-e9a0d180-130f-11eb-97e4-7270600a9b7a.png">

**Comment by matthewcosgrove** [comment]
```
Version:      7.0.0
Build:        16749670
```

**Comment by goneri** [comment]
Hi @matthewcosgrove, thank you for feedback,

I need to take a deeper look at this one, I though it was documented. I also use 7.0.0 and it should work.

**Comment by goneri** [comment]
So @matthewcosgrove, I think the main problem here is that you pass the cluster moid in the `parent` key, it should actually be the root resource pool.

You can get some examples here:
https://github.com/ansible-collections/vmware.vmware_rest/pull/155/files#diff-8ac773e210c2c4a5e31c56eb2fd543e0935c42d36f7dffb4795478bf1e6d0514

This content will be include in the modules documentation.

**Comment by matthewcosgrove** [comment]
I probed a bit more on this working directly with the api explorer, and see a different error. Everything I tried so far returns this error when I "post" to create a resource pool

```
{
    "type": "com.vmware.vapi.std.errors.invalid_argument",
    "value": {
        "messages": [
            {
                "args": [
                    "create"
                ],
                "default_message": "Invalid input for method: create",
                "id": "vapi.invoke.invalid.input"
            },
            {
                "args": [
                    "STRUCTURE",
                    "String"
                ],
                "default_message": "Bad cast: STRUCTURE -> String",
                "id": "vapi.data.bad.cast2"
            },
            {
                "args": [
                    "STRING",
                    "{{ com.vmware.vcenter.resource_pool.shares_info.level : { } }} "
                ],
                "default_message": "Type mismatch: STRING != {{ com.vmware.vcenter.resource_pool.shares_info.level : { } }} ",
                "id": "vapi.data.type.mismatch"
            }
        ]
    }
}
```

The only thing I could think of to investigate was if I was using the wrong parent moid.

Looking further into the depths of the vcenter object hierarchy, I established that the parent should be the default resource pool of the cluster rather than the cluster itself. In other words, what we see through the UI within Hosts and Clusters is not a true view of the hierarchy. It has been simplified to hide the real complexity.

Using govc, we can see a more truthful view of the hierarchy.

So if I manually create a new resource pool via the UI called "myrp", and then run the following script

```
new_resource_pool_name="myrp"
resource_pool_parent=/"${GOVC_DATACENTER}"/host/"${GOVC_CLUSTER}"/Resources
new_resource_pool_full_path=${resource_pool_parent}/"${new_resource_pool_name}"
echo "Self identifiers for new RP.."
govc pool.info -json "${new_resource_pool_full_path}" | jq .ResourcePools[0].Self
echo "Parent identifiers for new RP.."
govc pool.info -json "${new_resource_pool_full_path}" | jq .ResourcePools[0].Parent
echo "Self identifiers for parent of new RP.."
govc pool.info -json "${resource_pool_parent}" | jq .ResourcePools[0].Self
echo "Parent identifiers for parent of new RP.."
govc pool.info -json "${resource_pool_parent}" | jq .ResourcePools[0].Parent
```

We can see an output like this

```
Self identifiers for new RP..
{
  "Type": "ResourcePool",
  "Value": "resgroup-4073"
}
Parent identifiers for new RP..
{
  "Type": "ResourcePool",
  "Value": "resgroup-2051"
}
Self identifiers for parent of new RP..
{
  "Type": "ResourcePool",
  "Value": "resgroup-2051"
}
Parent identifiers for parent of new RP..
{
  "Type": "ClusterComputeResource",
  "Value": "domain-c2050"
}
```

Using any moid from this output in the api explorer to "post" the creation of the resource pool gives me the same error at the top of this post.

So for now my workaround is to go back to a scripted approach with govc where I can simply use absolute vcenter hierarchy paths and not worry about any moid or the fact that the POST feature of the vcenter API resource pools was only recently introduced (I've seen it wasn't available in v6.7 either) so might not be ready for prime time. Hopefully, you will be able to demonstrate otherwise.

govc solution:
```
new_resource_pool_name="automated-rp"
resource_pool_parent=/"${GOVC_DATACENTER}"/host/"${GOVC_CLUSTER}"/Resources
govc pool.create "${resource_pool_parent}"/"${new_resource_pool_name}"
```

Hope this helps

**Comment by goneri** [comment]
I agree, the whole thing is a bit complicated. The example here https://github.com/ansible-collections/vmware.vmware_rest/pull/155/files#diff-8ac773e210c2c4a5e31c56eb2fd543e0935c42d36f7dffb4795478bf1e6d0514 works fine. And the playbook will be run by the CI, so you can definitely build from that.

**Comment by matthewcosgrove** [comment]
@goneri Thanks for the quick turnaround and taking the time to write some tests around this that also document a working a approach. Much appreciated.

I see this has just been marked as a bug, but I think its more of a documentation improvement issue. In conclusion, I think what could be improved is providing

- A snippet examples section for resource pool akin to that found in [docs/vmware.vmware_rest.vcenter_datacenter_module.rst#examples](docs/vmware.vmware_rest.vcenter_datacenter_module.rst#examples)
- A re-worded explanation of the parent field which atm is "_Parent of the created resource pool.
When clients pass a value of this structure as a parameter, the field must be the id of a resource returned by vcenter_resourcepool_info. Required with state=['present']_"
- Some clarity regarding the difference between the fields "name" and "resource_pool". i.e. For creation purpose resource pool can be null
- Some clarity around what features are actually supported across versions of vcenter

**Comment by matthewcosgrove** [comment]
@goneri it looks like your test is also providing the snippet for the examples (it looks to me that they get auto-generated based on this). One observation I have is that you show selecting a cluster, but then you don't use it to filter the resource pools. So the parent being defined for the example is based on `{{ resource_pools.value[0].resource_pool }}` which is just the first returned from the array of all resource pools. But what if there are multiple clusters, shouldnt you be filtering by cluster when you query for the resource pool?

I think this is a general feedback as well. One drawback of the whole approach of filtering to return the array of objects then grabbing the first item by index, is that it feels somehow non-deterministic in some cases. Lots of room for error if you get the filter wrong.

**Comment by matthewcosgrove** [comment]
Dropping my working example here. I am using the cluster details response "my_cluster_details" which contains the moid of its default resource pool which can be used as the parent

```
- name: Create resource pool
  hosts: localhost
  vars:
    existing_cluster: "{{ lookup('env', 'GOVC_CLUSTER') }}"

  collections:
  - vmware.vmware_rest
  tasks:
  - name: "get parent cluster for resource pool"
    vcenter_cluster_info:
      filter_names:
      - "{{ existing_cluster }}"
    register: my_cluster
  - name: "get parent cluster details"
    vcenter_cluster_info:
      cluster: '{{ my_cluster.value[0].cluster }}'
    register: my_cluster_details
  - debug: msg="{{ my_cluster_details }}"
  - name: "ensure resource pool created"
    vcenter_resourcepool:
      name: "new-resource-pool"
      parent: "{{ my_cluster_details.value.resource_pool }}"
    register: my_resource_pool
  - debug: msg="{{ my_resource_pool }}"

```

Unfortunately, I am responsible for ensuring that its idempotent.

First run: works fine
Second run: `fatal: [localhost]: FAILED! => {"_debug_info": {"operation": "create", "status": 400}, "changed": false, "type": "com.vmware.vapi.std.errors.invalid_argument", "value": {"error_type": "INVALID_ARGUMENT", "messages": []}}`

Not an overly helpful error message there.

Would have hoped `state: present` results in automatic skipping logic implemented in the module. Maybe a downside of auto-generation from the API I suppose.

So finally, to ensure idempotency I have this solution:

```
- name: Create resource pool
  hosts: localhost
  vars:
    existing_cluster: "{{ lookup('env', 'GOVC_CLUSTER') }}"
    new_resource_pool_name: "new-resource-pool"

  collections:
  - vmware.vmware_rest
  tasks:
  - name: "get parent cluster for resource pool"
    vcenter_cluster_info:
      filter_names:
      - "{{ existing_cluster }}"
    register: my_cluster
  - name: "get parent cluster details"
    vcenter_cluster_info:
      cluster: '{{ my_cluster.value[0].cluster }}'
    register: my_cluster_details
  - debug: msg="{{ my_cluster_details }}"
  - name: "check resource pool exists"
    vcenter_resourcepool_info:
      filter_names: "{{ new_resource_pool_name  }}"
      filter_clusters: "{{ my_cluster_details.id }}"
    register: rp_already_exists
  - debug: msg="{{ rp_already_exists }}"
  - name: "ensure resource pool created"
    vcenter_resourcepool:
      name: "{{ new_resource_pool_name  }}"
      parent: "{{ my_cluster_details.value.resource_pool }}"
    register: my_resource_pool
    when: not rp_already_exists.value
  - debug: msg="{{ my_resource_pool }}"
```

**Comment by goneri** [comment]
> @goneri Thanks for the quick turnaround and taking the time to write some tests around this that also document a working a approach. Much appreciated.
> 
> I see this has just been marked as a bug, but I think its more of a documentation improvement issue. In conclusion, I think what could be improved is providing
> 
>     * A snippet examples section for resource pool akin to that found in [docs/vmware.vmware_rest.vcenter_datacenter_module.rst#examples](docs/vmware.vmware_rest.vcenter_datacenter_module.rst#examples)

These modules are auto-generated. The snippet will be injected automatically next time we refresh the modules.

>     * A re-worded explanation of the "parent" field which atm is "_Parent of the created resource pool.
>       When clients pass a value of this structure as a parameter, the field must be the id of a resource returned by vcenter_resourcepool_info. Required with state=['present']_"
> 
>     * Some clarity regarding the difference between the fields "name" and "resource_pool". i.e. For creation purpose "resource_pool" can be null
> 
>     * Some clarity around what features are actually supported across versions of vcenter

For the next points, we need to be able to overwrite the sections of the documentation. This is not something we can do yet. I opened the following new issue to trace that: https://github.com/ansible-collections/vmware.vmware_rest/issues/156

**Comment by goneri** [comment]
> @goneri it looks like your test is also providing the snippet for the examples (it looks to me that they get auto-generated based on this). One observation I have is that you show selecting a cluster, but then you don't use it to filter the resource pools. So the parent being defined for the example is based on `{{ resource_pools.value[0].resource_pool }}` which is just the first returned from the array of all resource pools. But what if there are multiple clusters, shouldnt you be filtering by cluster when you query for the resource pool?
> 
> I think this is a general feedback as well. One drawback of the whole approach of filtering to return the array of objects then grabbing the first item by index, is that it feels somehow non-deterministic in some cases. Lots of room for error if you get the filter wrong.

This is how the community.vmware modules work under the hood. This leads to surprise time to time and also has an impact on the performance. with the vmware.vmware_rest collection, we ask the user to be more explicit about the resource to manage. This is more a design decision, we are naturally open to discussion it but I would prefer to do that in another bug report.

Anyway, thanks for your feedback. It's really appreciated.

**Comment by goneri** [comment]
Regarding the idempotency issue, I've created a new issue with the content of your message, see: https://github.com/ansible-collections/vmware.vmware_rest/issues/157
