### ISSUE TITLE
rename repo to ansible.vmware_rest

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/vmware.vmware_rest#18]
##### SUMMARY

Hi, can we please rename the repo to be consistent with others under gh/anisble-collections?

GitHub will maintain redirects. Once done we should review README and galaxy.yml

**Comment by gundalow** [comment]
Or should this be under the `vmware.` namespace?
@thaumos

**Comment by goneri** [comment]
Yes, it should be `vmware.vmware_rest`.

**Comment by goneri** [comment]
Issue resolved.
