### ISSUE TITLE
Add modules/support for vRealize LogInsight

### ISSUE THREAD

**Issue by liamwh** [ansible-collections/vmware.vmware_rest#188]
##### SUMMARY
Create modules to deploy and configure vRealize LogInsight using Ansible.

Configure settings such as:
![image](https://user-images.githubusercontent.com/23312359/116867907-1c584a80-ac0e-11eb-8be3-b1b8599e9b64.png)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vRealize LogInsight modules, probably scraped from the vRLI API.

##### ADDITIONAL INFORMATION
Automated deployment/configuration of vRealize Operations Manager and it's integration with vSphere.
Contributes towards completion of Ansible modules available for the VMware vRealize suite.

```yaml
None exist yet for vRealize LogInsight. It is typically configured via the UI (but has API support).
```

**Comment by goneri** [comment]
I close this issue since it's a bit of a dup with https://github.com/ansible-collections/vmware.vmware_rest/issues/187.
