### ISSUE TITLE
aiohttp Python version requirement confusing

### ISSUE THREAD

**Issue by MallocArray** [ansible-collections/vmware.vmware_rest#244]
##### SUMMARY

On the main page:
https://github.com/ansible-collections/vmware.vmware_rest
there is conflicting information about what version of python is needed for aiohttp.

Under the heading "Python version compatibility" it says that it requires Python 3.7 or greater with a link to:
https://github.com/aio-libs/aiohttp#requirements

Under the heading of "install the dependencies" it says Python 3.6 or greater is required and has a link for aiohttp to a different site that supports this claim:
https://docs.aiohttp.org/en/stable/

Need to resolve the discrepancy. Does it need Python 3.6 or 3.7 as a minimum?  What version of aiohttp is required as the links refer to either 3.7.4.post0 or 3.7.3

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by goneri** [comment]
Hi @MallocArray,

vmware_rest works fine with aiohttp 3.7.4.post0 stable and Python 3.6. I will clarify the README file.
