### ISSUE TITLE
Error: Invalid datastore path mounting Content Library ISO in vcenter_vm cdrom

### ISSUE THREAD

**Issue by robbevl** [ansible-collections/vmware.vmware_rest#309]
I'm not sure how to specify a Content Library ISO to be mounted on a new VM. I looked but couldn't find anything in the docs.

    - name: Create VM
      vmware.vmware_rest.vcenter_vm:
        cdroms:
          - type: SATA
            start_connected: true
            backing:
              type: ISO_FILE
              iso_file: <Unsure what to put here>
[...]

I tried different conventions:
"[contentLib] /ISO File Library/my_iso_file.iso" (as that's the path you can see in the UI)
"[contentLib] ISO File Library/my_iso_file.iso"
"/ISO File Library/my_iso_file.iso"
"ISO File Library/my_iso_file.iso"
"5c634280-75b3-4886-bc67-e37f3dabd44f" (MoID)

Same error every time:
Request has failed: status=500, {"error_type":"ERROR","messages":[{"args":[],"default_message":"Invalid datastore path ''5c634280-75b3-4886-bc67-e37f3dabd44f''.","id":"vmsg.InvalidDatastorePath.summary"}]}

Just wondering - is this even supported?

**Comment by robbevl** [comment]
Ok, so after some research, it seems the REST API doesn't provide that functionality.
I could manage if I could build the datastore path to the ISO file, which is something like:
 [ mydatastore ] contentlib-<contentlib UUID>/<isofile UUID>/isofile.iso

Unfortunately it seems Vcenter adds another UUID between filename and extention, like so:
 [ mydatastore ] contentlib-<contentlib UUID>/<isofile UUID>/isofile-<unknown UUID>.iso

The only way to deal with that is to be able to search the files in a datastore and filter the list on "isofile". I don't think that functionality exists in ansible, so I'm throwing in the towel at this point. I'll stop using Content Library and put my ISO files on the datastore somewhere. Unless someone has a better idea.

I wonder why it's made so difficult to use the Content Library for automation though.


References:
https://www.lucd.info/2020/12/13/how-to-mount-a-content-library-iso-on-a-vm/

**Comment by jillr** [comment]
Hi @robbevl  That's definitely frustrating, unfortunately we're limited by what the API enables us to do.  It sounds like you have a work around with the datastore, so I'm glad to hear that!
