### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vmware.vmware_rest#332]
##### SUMMARY
We are running sanity tests across every collection included in the Ansible community package (as part of [this issue](https://github.com/ansible-community/community-topics/issues/96)).

I hope I've fixed all remaining problems in #331. However, since we're testing against the release that's part of the Ansible community package, and those fixes aren't part of a release yet, I think we'll run into failing tests once ~`community.vmware`~ `vmware.vmware_rest` [is added](https://github.com/ansible-community/community-topics/issues/99).

In order to avoid this, it would be really great if you could release a new version of this collection in time for Ansible 6.0.0a3 (Tuesday or Wednesday next week, I think).

cc @goneri @dmsimard 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
n/a

**Comment by goneri** [comment]
Hi @mariolenz, I'm not sure if the request is for community.vmware or vmware.vmware_rest.

**Comment by mariolenz** [comment]
@goneri `vmware.vmware_rest`. I've released a new version of `community.vmware`to fix this yesterday.

Ah, sorry! I think I have a C&P failure there!

**Comment by mariolenz** [comment]
I think it's already too late to get a current release of this collection into Ansible 6.0.0 :cry:
