### ISSUE TITLE
some modules have odd formatting in the short description

### ISSUE THREAD

**Issue by samccann** [ansible-collections/vmware.vmware_rest#337]
##### SUMMARY

Some modules have the following in their short description:

Retrieves information about the cluster corresponding to {@param.name cluster}
The `{@param.name cluster}` seems odd and there are 9 examples of  these odd short descriptions.

This shows up in Automation Hub as well as docs.ansible.com. 

Initial discussion reveals:

> The documentation is autogenerated and it looks like some artifacts remain from the original API documentation.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

https://github.com/ansible-collections/vmware.vmware_rest/blame/main/plugins/modules/vcenter_cluster_info.py

##### ANSIBLE VERSION

```paste below
2.13
```

**Comment by mikemorency** [comment]
this seems to have been an issue in older versions of the api spec. The descriptions dont have this phrasing anymore
