### ISSUE TITLE
Question: Where to ask questions about module usage and documentation?

### ISSUE THREAD

**Issue by Tronde** [ansible-collections/vmware.vmware_rest#403]
##### SUMMARY

I would like to know whether there is some sort of mailing-list or forum to ask user questions regarding the usage of this collection and it's modules as well as the documentation when something seems to be unclear.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

guide_vmware_rest.rst

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tronde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/tronde/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

Where to ask questions like:

- Does it not work? Or do I just hold it wrong?
- I don't understand the docs in this point. Who can explain?
- I would like to do this, but don't know how. Who could help?

Looking forward reading your answer.

Best regards,  
Tronde

**Comment by mariolenz** [comment]
Maybe the [forum](https://forum.ansible.com/) that we've created a few months ago would be the best place to ask any questions.
