### ISSUE TITLE
"Edit on GitHub" link seems to be missing on documentation pages

### ISSUE THREAD

**Issue by Tronde** [ansible-collections/vmware.vmware_rest#404]
##### SUMMARY
The Documentation Report template includes the following hint:
~~~
<!--- HINT: Did you know the documentation has an "Edit on GitHub" link on every page ? -->
~~~

But looking at the documentation using current versions of Chrome and Firefox browsers I couldn't find this link anymore anywhere on the pages. I guess this link might have been removed in a recent release.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

- [vmware.vmware_rest.vcenter_vm_module.rst](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_vm_module.rst)
- [vmware.vmware_rest.vcenter_cluster_info_module.rst](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_cluster_info_module.rst)
- [vmware.vmware_rest.vcenter_datacenter_info_module.rst](https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_datacenter_info_module.rst)

These are only the ones I checked, but I think they are all affected.

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.3]
```

I guess the ansible version does not matter.

**Comment by gravesm** [comment]
Thank you for filing an issue. The link to edit the docs on github appears as a pencil icon which you can see along the top bar of the document when viewing on github. Do note, however, that the docs for this collection are automatically generated, so any changes to the documentation files would be overwritten.

Is there a specific problem with the docs that you have found?

**Comment by Tronde** [comment]
OK, my mistake. I looked at: https://docs.ansible.com/ansible/latest/collections/vmware/vmware_rest/vcenter_vm_module.html#ansible-collections-vmware-vmware-rest-vcenter-vm-module for the edit button but found it at https://github.com/ansible-collections/vmware.vmware_rest/blob/main/docs/vmware.vmware_rest.vcenter_vm_module.rst.

I thoughed when I find some typo I could just fix it real quick or contribute an example by adding it at the appropriate place. But I understood that the documentation is auto-generated and small fixes are not that easy to contribute.

**Comment by Tronde** [comment]
Hi @gravesm,  
Did my last comment answer your question or do you still need additional info?

**Comment by gravesm** [comment]
@Tronde yes, thanks. Is there a remaining question here, or can we close this?
