### ISSUE TITLE
Does this collection work for vSphere 8.0 as well?

### ISSUE THREAD

**Issue by sugitk** [ansible-collections/vmware.vmware_rest#407]
##### SUMMARY

The documentation describes `The 2.0.0 version of this collection requires vSphere 7.0.2 or greater.` as the compatibility, does the `greater` include 8.0 as well?

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by sugitk** [comment]
The customer requests a confirmation regarding this issue.  Could someone check it whether it works on 8.0 or not?

**Comment by sugitk** [comment]
Today I have upgraded my vCenter from 7.0.3 to 8.0.1 and tested some playbooks.

- https://github.com/sugitk/ansible-my-vcenter/blob/main/newapi.yml
- https://github.com/sugitk/ansible-my-vcenter/blob/main/rest_clone_rhel8.yml

I found the playbooks worked fine even for 8.0.1 as well on my side.  Here is the version information that I tested.

```
$ ansible --version
ansible [core 2.14.6]
  config file = /Users/sugimura/github/ansible-my-vcenter/ansible.cfg
  configured module search path = ['/Users/sugimura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/sugimura/venv/XXXXXX/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/sugimura/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/sugimura/venv/XXXXXX/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/sugimura/venv/XXXXXX/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
$ ansible-config dump --only-changed
CONFIG_FILE() = /Users/sugimura/github/ansible-my-vcenter/ansible.cfg
HOST_KEY_CHECKING(/Users/sugimura/github/ansible-my-vcenter/ansible.cfg) = False
$ ansible-galaxy collection list | grep vmware_rest
vmware.vmware_rest            2.3.1  
```

For maintainers, could you please add information in the section of "vSphere compatibility" in the README.md file if you confirmed?

**Comment by keilr** [comment]
@goneri is there any news regarding vsphere 8 support?
