### ISSUE TITLE
Better documentation how this collection is generated

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vmware.vmware_rest#423]
##### SUMMARY
I don't understand how this collection is generated. Is this documented? [This](https://github.com/ansible-community/ansible.content_builder#5-vmwarevmware_rest) doesn't really help...

It would be really helpful to have a complete example how to create a module from the OpenAPI / Swagger specification. Maybe this exists and I just didn't find it. In this case please point me to it.

If there's no example, it would be really helpful if you could create an example how to create a module from an OpenAPI / Swagger specification.

BTW, it looks like you're depending on `https://github.com/goneri/ansible-collection-goneri.utils.git`. I think this is a problem... nothing against @goneri but we shouldn't rely on repos owned by a single person.

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

cc @jillr

**Comment by GomathiselviS** [comment]
Hello @mariolenz , 

Thank you for filing this issue. As mentioned in the [README](https://github.com/ansible-community/ansible.content_builder/blob/main/README.md), we're still using Goneri's private repo for the refresh of the return block. However, we do have plans to move the scripts to the content_builder repo in the future. I'm currently working on creating a detailed example and will share the PR with you soon. In the meantime, you can create a manifest.yaml file similar to the one provided [here](https://github.com/ansible-community/ansible.content_builder/blob/main/README.md#5-vmwarevmware_rest). To generate the modules, you can use it as shown [here](https://github.com/ansible-community/ansible.content_builder/blob/main/README.md#using-this-collection). The parameters you'll need to use in the manifest.yaml file are explained [here](https://github.com/ansible-community/ansible.content_builder/blob/main/README.md#resource-module-scaffolding-generated-using-openapi-based-json) .

**Comment by GomathiselviS** [comment]
@mariolenz Please review #424

**Comment by mariolenz** [comment]
@GomathiselviS #424 fails [ansible-test-sanity-docker-milestone](https://ansible.softwarefactory-project.io/zuul/build/1e264cf752994e7890de95bc1c4d8c43) test:

```
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:97:0: unused-import: Unused import socket
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused build_full_device_list imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused exists imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused get_device_info imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused get_subdevice_type imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused list_devices imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
ERROR: plugins/modules/vcenter_vmtemplate_libraryitems_info.py:111:0: unused-import: Unused prepare_payload imported from ansible_collections.vmware.vmware_rest.plugins.module_utils.vmware_rest
```

```
ERROR: plugins/modules/vcenter_vm_hardware_adapter_sata.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
ERROR: plugins/modules/vcenter_vm_hardware_adapter_scsi.py:0:0: doc-default-does-not-match-spec: Argument 'bus' in argument_spec defines default as (0) but documentation defines default as (None)
```

How would I fix this? Especially the first one since I don't see where those imports are defined as a requirement for the module. That is, except in the (generated) module itself.
