### ISSUE TITLE
VCenter appliance root password expiration set ...

### ISSUE THREAD

**Issue by kkrishnasamy01** [ansible-collections/vmware.vmware_rest#459]
Hi Team,

Please share me module name for "VCenter appliance root password expiration set".
Getting "ERROR! couldn't resolve module/action 'vmware.vmware_rest'. This often indicates a misspelling, missing collection, or incorrect module path."

below is my playbook

---
-  hosts: localhost
   name: VC Root Password Expiration Set
   gather_facts: false
   vars_files: ../answerfile.yml

   tasks:
     - name: Password Expiration Set
       vmware.vmware_rest:
         hostname: "{{ vcenter_hostname }}"
         username: "{{ vcenter_username }}"
         password: "{{ vcenter_password }}"
         validate_certs: no
         #max_days_between_password_change: 9999
         #min_days_between_password_change: 6
         #warn_days_before_password_expiration: 7
         root_password_expires: "{{ expire_password }}"
         root_password_expire_days: "{{ password_expiration_days }}"
         state: present
       delegate_to: localhost

**Comment by mariolenz** [comment]
Issues are not meant to ask general usage questions. They should be used for feature requests, bug reports and similar.

Please ask somewhere else. Maybe the [forum](https://forum.ansible.com/) might be a good place. There's a `Get Help` category and you can even tag your question with `vmware`.
