### ISSUE TITLE
Deprecate some modules

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/vmware.vmware_rest#502]
##### SUMMARY
Since [vmware.vmware](https://github.com/ansible-collections/vmware.vmware) provides a [vcsa_settings module](https://github.com/ansible-collections/vmware.vmware/blob/dcae82c253666f88110133786a41ed1c0382a682/plugins/modules/vcsa_settings.py) and is now part of the Ansible community package, it might be a good idea to deprecate some modules in this collection in favour of using the new one.

There might be some more, but these are the ones I've already identified.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
appliance_access_consolecli
appliance_access_dcui
appliance_access_shell
appliance_access_ssh
appliance_networking_dns_domains
appliance_networking_dns_servers
appliance_ntp
appliance_system_time_timezone
appliance_timesync

##### ADDITIONAL INFORMATION
Since this collection is generated, maybe the generator should support this: ansible-community/ansible.content_builder#88

**Comment by MallocArray** [comment]
This is the first I'm hearing of vmware.vmware and not clear if it is more "official" than this repo.  I generally trust vmware.vmware_rest more than community.vmware to be more direct API interaction rather than lots of extra manipulation, but unclear where vmware.vmware fits into this model or why it would mean it is time to remove functionality here, forcing users to make a change to a new collection.

**Comment by mariolenz** [comment]
> This is the first I'm hearing of vmware.vmware and not clear if it is more "official" than this repo.

It's been [announced in the forum](https://forum.ansible.com/t/5880) (although this post is focused on `community.vmware`) and also turns up as a new release in the Ansible Community Package (ACP) :smirk: 

> I generally trust vmware.vmware_rest more than community.vmware to be more direct API interaction rather than lots of extra manipulation

I disagree. If you want to have "more direct API interaction" you should use the API directly. I think ansible modules should abstract from the API and do _useful_ stuff. They shouldn't be just (another) API wrapper.

For example, I'm really looking forward to seeing `vmware.vmware.vcsa_settings` in the ACP because it would allow us to have just one task instead of halve a dozen or more. If I want to configure the vCSA, the usability is much better if I could do it in one go instead of having to run several ones just because the API is built like this ;-)

> it would mean it is time to remove functionality here, forcing users to make a change to a new collection

The alternative is that we have to maintain the same functionality in two (or maybe even three) collections. This costs time, which means we can't work on other stuff that might be even more important than making sure users don't have to simply use a module from another collection.

Out of curiosity, did you have a look at `vmware.vmware.vcsa_settings` yet? I really think it's an improvement. Do you see any problems there? I'm afraid it's not released yes, but I hope (@bardielle @mikemorency *hint* *hint*) we'll see 1.4.0 soon.

**Comment by mikemorency** [comment]
vmware.vmware 1.4.0 should be released in the next 2-3 weeks

I think modules with outstanding feature requests or issues are good candidates for deprecation (assuming a new module with similar functionality is present). Since this repo is primarily autogenerated, a working module has very little maintenance overhead. It makes sense to me to leave those working modules in place even if functionality is redundant.

I could see it being confusing to new users when they search for modules though.

**Comment by mariolenz** [comment]
> vmware.vmware 1.4.0 should be released in the next 2-3 weeks

This sounds a little bit late for Ansible 10.3.0, which I think will be released 2024-08-13. Take your time, I don't want to put any pressure on you. Just wanted to mention this.

> Since this repo is primarily autogenerated, a working module has very little maintenance overhead. It makes sense to me to leave those working modules in place even if functionality is redundant.

So you prefer the "don't fix what ain't broken" approach? I'm not 100% sure if I agree, but I won't object if you close this issue. I admit that that you have a point there :-)

> I could see it being confusing to new users when they search for modules though.

Maybe it would help to mention `vmware.vmware.vcsa_settings` in those modules. What do you think about #506 as a compromise? Unfortunatelly, it fails the CI and and I don't understand why :-(

**Comment by mariolenz** [comment]
OK, let's not deprecate those modules but at least mention the new module module in `vmware.vmware`: #506
