### ISSUE TITLE
Bug in content_library_item_info module in Version 4.0.0 and higher

### ISSUE THREAD

**Issue by jasondickerson** [ansible-collections/vmware.vmware_rest#532]
### Summary

When using content_library_item_info module to pull the list of items in a content library, I am encountering an error returned by the vmware rest API:

    "value": {
        "error_type": "INVALID_ARGUMENT",
        "messages": [
            {
                "args": [
                    "library_id?library_id"
                ],
                "default_message": "Unsupported property with name: library_id?library_id.",
                "id": "com.vmware.vapi.rest.unsupportedProperty"
            }
        ]
    }
    
I believe I have tracked the bug down to line 292 - 298
    
    292         return yarl.URL(
    293         ("https://{vcenter_hostname}" "/api/content/library/item?library_id").format(
    294             **params
    295         )
    296         + gen_args(params, _in_query_parameters),
    297         encoded=True,
    298     )

When line 296 is invoked it adds library_id into the parameter list.  However, as you see on line 293 libary_id is already in the parameter list, hard coded.  When I change line 293 to the following:

    293         ("https://{vcenter_hostname}" "/api/content/library/item").format(

the module works again.  

The issue was introduced in:  

https://github.com/ansible-collections/vmware.vmware_rest/pull/511/commits/f40284f82f3b328d616a08a4f335fb97f76a7efe#diff-a8246069a43b1b7852610e3c07751068a2dd3bd0a0a48a6cdac2e2edc9306260

I have tested this with VMWare v7.0 u3 (v7.0.3).  The latest version of the collection with this module working is v3.1.0.  

### Issue Type

Feature Idea

### Component Name

content_library_item_info module 

### Additional Information

Thanks to techgirlgeek for assisting me to track this bug down.  

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by mikemorency** [comment]
Hey @jasondickerson 

I see in the issue you mention seeing the problem on vsphere 7.X while using version 4.X of this collection. 

Version 4.X of this collection is only compatible with the vsphere 8.X api. Version 3.X of this collection is only compatible with vsphere 7.X  api. While some modules may be backwards compatible (if VMware didnt change the API endpoints), other modules are not. This happens to be one of the modules that is not backwards compatible
